version: "3.8"

services:
  calendar:
    image: otus-golang/calendar:develop
    environment:
      CALENDAR_STORAGE_PGSQL_HOST: pgsql
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: on-failure
    depends_on:
      - rabbitmq
      - pgsql

  scheduler:
    image: otus-golang/calendar-scheduler:develop
    environment:
      SCHEDULER_QUEUE_RABBITMQ_ADDRESS: rabbitmq
      SCHEDULER_STORAGE_PGSQL_HOST: pgsql
    restart: on-failure
    depends_on:
      - rabbitmq
      - pgsql
    command: sh -c 'calendar-scheduler --config /etc/calendar/config.toml --scan_interval 5s'

  sender:
    image: otus-golang/calendar-sender:develop
    environment:
      SENDER_QUEUE_RABBITMQ_ADDRESS: rabbitmq
      SENDER_WRITER_TARGET_FILE: /tmp/writer.txt
    restart: on-failure
    depends_on:
      - rabbitmq
      - pgsql
    volumes:
      - /tmp:/tmp
    command: sh -c 'calendar-sender --config /etc/calendar/config.toml'

  rabbitmq:
    image: rabbitmq:3.11.1
    ports:
      - "5672:5672"

  pgsql:
    image: postgres:15.0
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: