version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.11.1
    ports:
      - "5672:5672"

  db:
    image: postgres:15.0
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: