version: "3.8"

services:
  calendar:
    image: otus-golang/calendar:develop
    ports:
      - "8888:8080"
    restart: always

  scheduler:
    image: otus-golang/calendar-scheduler:develop
    environment:
      SCHEDULER_QUEUE_RABBITMQ_ADDRESS: rabbitmq
    restart: always
    depends_on:
      - rabbitmq

  sender:
    image: otus-golang/calendar-sender:develop
    environment:
      SENDER_QUEUE_RABBITMQ_ADDRESS: rabbitmq
    restart: always
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.11.1


