[http]
address = "localhost"
port = 8080

[grpc]
address = "localhost"
port = 8081

[logger]
level = "INFO"

[storage]
type = "pgsql"

[storage.pgsql]
host = "localhost"
port = "5432"
username = "postgres"
password = "password"
database = "postgres"
