[http]
address = ""
port = 8080

[grpc]
address = ""
port = 8081

[logger]
level = "INFO"

[storage]
type = "memory"

[storage.pgsql]
host = "localhost"
port = "5432"
username = "postgres"
password = ""
database = "postgres"
