[queue]
type = "rabbitmq"

[queue.rabbitmq]
address = "localhost"
port = 5672
username = "guest"
password = "guest"
queue_name = "events_notifications"

[sender]
type = "writer"

[writer]
target_file = ""
