version: "3.8"

services:
  calendar:
    image: otus-golang/calendar:develop
    environment:
      CALENDAR_STORAGE_PGSQL_HOST: pgsql
    restart: on-failure
    depends_on:
      - rabbitmq
      - pgsql

  scheduler:
    image: otus-golang/calendar-scheduler:develop
    environment:
      SCHEDULER_QUEUE_RABBITMQ_ADDRESS: rabbitmq
      SCHEDULER_STORAGE_PGSQL_HOST: pgsql
    restart: on-failure
    depends_on:
      - rabbitmq
      - pgsql
    command: sh -c 'sleep 15 && calendar-scheduler --config /etc/calendar/config.toml --scan_interval 5s'

  sender:
    image: otus-golang/calendar-sender:develop
    environment:
      SENDER_QUEUE_RABBITMQ_ADDRESS: rabbitmq
      SENDER_WRITER_TARGET_FILE: /tmp/writer.txt
    restart: on-failure
    depends_on:
      - rabbitmq
      - pgsql
    volumes:
      - tmp:/tmp
    command: sh -c 'sleep 15 && calendar-sender --config /etc/calendar/config.toml'

  rabbitmq:
    image: rabbitmq:3.11.1

  pgsql:
    image: postgres:15.0
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password

  migrator:
    image: otus-golang/calendar:develop
    environment:
      CALENDAR_STORAGE_PGSQL_HOST: pgsql
    restart: on-failure
    depends_on:
      - pgsql
    command: /bin/sh -c 'sleep 15 && calendar-migrate --config /etc/calendar/config.toml --command up && sleep 120'

  tester:
    image: otus-golang/base:develop
    working_dir: /usr/src/calendar
    volumes:
      - ../..:/usr/src/calendar
      - tmp:/tmp
    environment:
      TESTS_HTTP_SERVER_HOST: calendar
      TESTS_GRPC_SERVER_HOST: calendar
      TESTS_DATABASE_HOST: pgsql
      TESTS_RQBBITMQ_HOST: rabbitmq
      TESTS_WRITER_TARGET_FILE: /tmp/writer.txt
    depends_on:
      - pgsql
      - rabbitmq
    command: [ "go", "test", "-v", "-tags=integration", "./internal/tests/integration/..."]


volumes:
  tmp:
