version: "3.8"

services:
  calendar:
    image: otus-golang/calendar:develop
    expose:
      - 8080
    restart: on-failure

  scheduler:
    image: otus-golang/calendar-scheduler:develop
    environment:
      SCHEDULER_QUEUE_RABBITMQ_ADDRESS: rabbitmq
    restart: on-failure
    depends_on:
      - rabbitmq

  sender:
    image: otus-golang/calendar-sender:develop
    environment:
      SENDER_QUEUE_RABBITMQ_ADDRESS: rabbitmq
      SENDER_SENDER_WRITER_TARGET_FILE: /tmp/writer.txt
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes:
      - /tmp:/tmp
    command: sh -c 'sleep 5 && calendar-sender --config /etc/calendar/config.toml'

  rabbitmq:
    image: rabbitmq:3.11.1


  tester:
    image: golang:1.17.13
    working_dir: /usr/src/calendar
    volumes:
      - ../..:/usr/src/calendar
      - /tmp:/tmp
    environment:
      TESTS_HTTP_SERVER_HOST: calendar
      TESTS_RQBBITMQ_HOST: rabbitmq
      TESTS_WRITER_TARGET_FILE: /tmp/writer.txt
    command: [ "go", "test", "-tags=integration", "./internal/tests/integration/..."]


